name: 'Run API tests against Sample Book App'
description: 'Run API tests against Sample Book App inside docker contaienr'
inputs:
  environment:
    description: 'Environment where to run Sample Book App tests against'
    required: true
runs:
  using: composite
  steps:
    - name: Pull api-tests docker image
      run: docker pull mtararujs/api-tests
      shell: bash
    - name: Run API tests
      run: docker run --rm --network sample-book-app-compose-network -v $PWD/test-reports:/api-tests/mochawesome-report mtararujs/api-tests run BOOKS BOOKS_${{ inputs.environment }}
      shell: bash
name: Sample Book App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: self-hosted
    needs: [build-docker-image]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
            environment: 'dev'
  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
            environment: 'DEV'
  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
            environment: 'stg'
  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
            environment: 'STG'
  deploy-prd:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
            environment: 'prd'
  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
            environment: 'PRD'